name: Deploy Main

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            set -e
            
            cd /opt/discord-bot || exit 1
            
            git pull origin main
            
        
            docker compose down
            docker compose up --build -d
            
            docker system prune -f
            docker-compose ps
            
            echo "Деплой успешен"